#!/usr/bin/env php
<?php

define('START_TIME', microtime(true));

require_once 'app/Kernel.php';

/**
 * Create kernel this console application then
 * Make console object and run it
 * 
 * it's simple
 */

exit(Kernel::console()
    ->make(\Core\Support\Console::class, array($argv))
    ->run());
