#!/usr/bin/env php
<?php

define('startTime', microtime(true));

require_once 'app/env.php';
require_once 'app/bootstrap.php';
require_once 'helpers/helpers.php';

/**
 * Create container this application then
 * Build console object and run it
 * 
 * it's simple
 */
$app = \Core\App::new(new \Core\Application());

$console = $app->singleton(\Core\Console::class, array($argv));
exit($console->run());
